### ISSUE TITLE
7.1.1 - Airplane Mode no longer seems to be enabled on post-boot Emergency Call/Pre-Encryption Password screen

### ISSUE THREAD

**Issue by cypherpunkglobal** [copperhead/bugtracker#524]
Prior to the version 7.1.1 upgrade (i.e. prior to build 2016.12.06.05.21.23), if airplane mode was enabled in the main OS, an airplane mode symbol was visible on the post-boot unlock/emergency call screen in the status bar. If the emergency call button was pressed, airplane mode would be disabled and the airplane mode icon would disappear. Upon reboot, the icon would reappear once again.

After build 2016.12.06.05.21.23, this does not seem to be the case, even with airplane mode enabled in the main OS. When you arrive at the unlock/emergency screen, no status bar icons are visible and it is unclear whether airplane mode is enabled. I have yet to fully test whether cellular radios get enabled in this mode.

Given that it is probably not a great idea to have the device pinging cell towers without users’ knowledge, and this is a security- and privacy-oriented OS, I thought it would be good to bring this up.

**Comment by thestinger** [comment]
It can't know if airplane mode is enabled in the OS there, since the data partition isn't mounted. So it wasn't doing what you think before, but maybe it does work different now beyond simply a UX change. It can't know the OS setting though.

**Comment by cypherpunkglobal** [comment]
Really? If airplane mode disables radios, I can't see why it isn't possible for the state set in the main OS to be set in persistent flash, or at least somewhere outside the data partition. Either way, I guess my point is that airplane mode was definitely present on this screen prior to this update and that it no longer seems to be. Is there any way of testing this other than measuring signals using test points on the logic board or measuring RF in lab conditions? I don't have access to equipment right now.

**Comment by thestinger** [comment]
> Is there any way of testing this other than measuring signals using test points on the logic board or measuring RF in lab conditions?

You can make a userdebug build and test whatever you want. You're really moved onto a different issue now.

**Comment by thestinger** [comment]
> Either way, I guess my point is that airplane mode was definitely present on this screen prior to this update and that it no longer seems to be.

That doesn't really mean anything without looking into what they actually changed. This functionality is also already deprecated since it's tied to FDE which will be going away on new devices. Any problem tied to the limitations of FDE is solved by us moving to the Pixel / Pixel XL.

**Comment by thestinger** [comment]
FBE is technically available for the 5X and 6P too.

**Comment by thestinger** [comment]
Not going to be doing work on upstream issues with FDE support, which is effectively obsolete now.

**Comment by cypherpunkglobal** [comment]
I know you've closed this issue, but I want to confirm this issue still exists and that cellular radios do get enabled. It is not as if Android's FDE even is full volume or real full disk encryption, it is partition encryption, i.e. only the /data, /sdcard partitions are encrypted. The airplane mode icon used to be displayed on this screen pre-7.1 unless you touched Emergency Call, at which point it was disabled. Many devices that use full disk encryption have separate software control of radios, e.g. using NVRAM, etc. If the radios have been disabled while in the main OS, they should remain off whether the encryption password has been entered or not.

The battery history details page shows that, despite airplane being enabled, during a reboot cellular radios are enabled until the FDE password is entered.

**Comment by thestinger** [comment]
FDE is "real" full disk encryption and there's no such thing as an /sdcard partition. All persistent state is in /data and the OS partitions are covered by verified boot and are publicly available data anyway.
